services:
  mongodb:
    image: mongo:4.4.6
    container_name: event_mongo
    restart: unless-stopped
    env_file:
      - ./cmd/.env
    ports:
      - 2717:27017

  redis:
    image: redis:latest
    container_name: event_redis
    restart: unless-stopped
    env_file:
      - ./cmd/.env
    ports:
      - 6378:6379

  client:
    image: authenicator
    container_name: event_client
    restart: unless-stopped
    env_file:
      - ./cmd/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - 8081:8081
    
